# Generated by Django 4.2.7 on 2023-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=10, null=True),
        ),
    ]
